services:
  agent-miner:
    image: redteamsubnet61/agent-miner:1.1.0-251215
    # volumes:
    #   - "agent-miner-vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "8"
    #       memory: 16G
    # command: ["/bin/bash"]


# volumes:
#   agent-miner-vscode-server:
