services:
  agent-miner:
    image: redteamsubnet61/agent-miner:latest
    volumes:
      - "./volumes/storage/sidecar-btcli/data:${RT_BTCLI_DATA_DIR:-/var/lib/sidecar-btcli}"
      - "./volumes/storage/agent-miner/logs:${RT_MINER_LOGS_DIR:-/var/log/agent-miner}"
      - "./volumes/storage/agent-miner/data:${RT_MINER_DATA_DIR:-/var/lib/agent-miner}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./src:/app/agent-miner"
      - "./volumes/.vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 8G
    # command: ["/bin/bash"]
